# QCCD Hardware Parameters
hardware:
  trap_capacity: [2,5,10,120] 
  topology: "grid" 

# QEC Code Properties
qec:
  code_type: (6.6.6)
  distances: [3,5,7,9]  
  gate_improvements: [1.0]

# Simulation Settings
simulation:
  rounds: 1  
  num_shots: 1000000  
  log_file: process_log.txt  
