# QCCD Hardware Parameters
hardware:
  trap_capacity: [3]  
  topology: "grid" 

# QEC Code Properties
qec:
  code_type: "surface_code:rotated_memory_z"
  distances: [5]  
  gate_improvements: [1.0]

# Simulation Settings
simulation:
  rounds: 1  
  num_shots: 1000000  
  log_file: process_log.txt  
